-- Create the suggestions table
create table suggestions (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  password text, -- Optional, only for secret posts
  is_secret boolean default false
);

-- Set up Row Level Security (RLS)
-- For this simple app, we might want to allow public read/write for simplicity, 
-- or restrict based on requirements. 
-- Since there's no auth system mentioned other than the ad-hoc password:
alter table suggestions enable row level security;

-- Allow anyone to read suggestions (we filter content client-side or via policy if possible, 
-- but for "secret" posts with client-side password check, we technically need to fetch them to check the password? 
-- Actually, if we want to be secure, we should use a function, but the requirement says "client side check" logic is fine for this level).
-- Let's just allow public access for now as per the "Outing" app pattern which seems to use anon key for everything.

create policy "Enable read access for all users" on suggestions for select using (true);
create policy "Enable insert access for all users" on suggestions for insert with check (true);
create policy "Enable update access for all users" on suggestions for update using (true);
create policy "Enable delete access for all users" on suggestions for delete using (true);

-- Add columns for admin reply
alter table suggestions add column if not exists admin_reply text;
alter table suggestions add column if not exists admin_reply_created_at timestamp with time zone;
